controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

excel_to_json:
    path: '/convert-excel-to-json'
    controller: 'App\Controller\ExcelToJsonController::convertExcelToJson'
    methods: ['POST']